### ISSUE TITLE
Fix error thrown by docker-compose up script

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#174]
When I run the `docker-compose up` script, I sometimes see the following error locally and do not see the latest generated CSS:

```
web_1  | generate css...
web_1  | /code/node_modules/node-sass/lib/binding.js:15
web_1  |       throw new Error(errors.missingBinary());
web_1  |       ^
web_1  | 
web_1  | Error: Missing binding /code/node_modules/node-sass/vendor/linux-x64-64/binding.node
web_1  | Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 10.x
web_1  | 
web_1  | Found bindings for the following environments:
web_1  |   - OS X 64-bit with Node.js 10.x
web_1  | 
web_1  | This usually happens because your environment has changed since running `npm install`.
web_1  | Run `npm rebuild node-sass` to download the binding for your current environment.
web_1  |     at module.exports (/code/node_modules/node-sass/lib/binding.js:15:13)
web_1  |     at Object.<anonymous> (/code/node_modules/node-sass/lib/index.js:14:35)
web_1  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
web_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
web_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
web_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
web_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
web_1  |     at Module.require (internal/modules/cjs/loader.js:692:17)
web_1  |     at require (internal/modules/cjs/helpers.js:25:18)
web_1  |     at Object.<anonymous> (/code/node_modules/gulp-sass/index.js:162:21)
web_1  | collect static assets...
```

**Comment by LindsayYoung** [comment]
wanted to confirm you are not having this problem anymore before we close this @alexsoble

**Comment by alexsoble** [comment]
@LindsayYoung I'm still seeing this problem locally — is there a step I need to run to make sure it goes away?

**Comment by LindsayYoung** [comment]
Did you delete your node modules have have them rebuild by running `docker-compose up`?

**Comment by LindsayYoung** [comment]
this is pretty old we can re-open if someone has this issue again
